[package]
name = "barred-owl"
version = "0.1.0"
authors = ["Eugenio Salvador Arellano Ruiz <euarellano2192@gmail.com"]
description = "Ontology visualisation library"

[dependencies]
horned-owl = "0.14.0"
layout-rs = "0.1.2"
