[package]
name = "barred-owl"
version = "0.1.0"
authors = ["Eugenio Salvador Arellano Ruiz <euarellano2192@gmail.com"]
description = "Ontology visualisation library"

[dependencies]
horned-owl = { git = "https://github.com/phillord/horned-owl.git", branch = "devel" }
layout-rs = "0.1.2"
