[package]
name = "barred-owl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
horned-owl = "0.14.0"
layout-rs = "0.1.2"
